2023-12-05T06:49:51.488Z - info: [gme] Node version v20.10.0
2023-12-05T06:49:51.488Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-05T06:49:51.488Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-05T06:49:51.494Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.2:8888
2023-12-05T06:49:51.544Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-05T06:49:51.546Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/miniproject
2023-12-05T06:49:51.554Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-05T06:49:51.554Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-05T07:29:10.614Z - info: [gme] Node version v20.10.0
2023-12-05T07:29:10.615Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-05T07:29:10.615Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-05T07:29:10.620Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.2:8888
2023-12-05T07:29:10.674Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-05T07:29:10.675Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/miniproject
2023-12-05T07:29:10.683Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-05T07:29:10.683Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-05T07:54:04.340Z - info: [gme] Node version v20.10.0
2023-12-05T07:54:04.340Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-05T07:54:04.341Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-05T07:54:04.345Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.2:8888
2023-12-05T07:54:04.391Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-05T07:54:04.392Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/miniproject
2023-12-05T07:54:04.398Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-05T07:54:04.399Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-05T07:54:34.305Z - info: [gme] Node version v20.10.0
2023-12-05T07:54:34.305Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-05T07:54:34.305Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-05T07:54:34.311Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.2:8888
2023-12-05T07:54:34.371Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-05T07:54:34.372Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/miniproject
2023-12-05T07:54:34.380Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-05T07:54:34.381Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-05T07:55:43.411Z - info: [gme] Node version v20.10.0
2023-12-05T07:55:43.411Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-05T07:55:43.411Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-05T07:55:43.417Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.2:8888
2023-12-05T07:55:43.470Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-05T07:55:43.471Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-05T07:55:43.480Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-05T07:55:43.480Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-05T08:00:56.449Z - info: [gme] Node version v20.10.0
2023-12-05T08:00:56.449Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-05T08:00:56.449Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-05T08:00:56.455Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.2:8888
2023-12-05T08:00:56.507Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-05T08:00:56.509Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-05T08:00:56.517Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-05T08:00:56.517Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-05T08:02:20.143Z - info: [gme] Node version v20.10.0
2023-12-05T08:02:20.143Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-05T08:02:20.143Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-05T08:02:20.149Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.2:8888
2023-12-05T08:02:20.202Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-05T08:02:20.203Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-05T08:02:20.218Z - warn: [gme:server:auth:gmeauth] User "guest" was not found. We will attempt to create it automatically.
2023-12-05T08:02:20.306Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-05T08:02:20.434Z - info: [gme:server:standalone] Server is listening ...
2023-12-05T08:22:00.318Z - info: [gme] Node version v20.10.0
2023-12-05T08:22:00.318Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-05T08:22:00.318Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-05T08:22:00.324Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.2:8888
2023-12-05T08:22:00.379Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-05T08:22:00.381Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-05T08:22:00.388Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-05T08:22:00.388Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-05T08:22:12.998Z - info: [gme] Node version v20.10.0
2023-12-05T08:22:12.998Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-05T08:22:12.998Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-05T08:22:13.004Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.2:8888
2023-12-05T08:22:13.053Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-05T08:22:13.054Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-05T08:22:13.081Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-05T08:22:13.203Z - info: [gme:server:standalone] Server is listening ...
2023-12-05T16:51:15.048Z - info: [gme] Node version v20.10.0
2023-12-05T16:51:15.048Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-05T16:51:15.048Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-05T16:51:15.054Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://10.74.206.210:8888
2023-12-05T16:51:15.109Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-05T16:51:15.111Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-05T16:51:15.118Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-05T16:51:15.119Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-05T16:51:39.388Z - info: [gme] Node version v20.10.0
2023-12-05T16:51:39.388Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-05T16:51:39.388Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-05T16:51:39.394Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://10.74.206.210:8888
2023-12-05T16:51:39.441Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-05T16:51:39.443Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-05T16:51:39.468Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-05T16:51:39.592Z - info: [gme:server:standalone] Server is listening ...
2023-12-06T04:51:07.684Z - info: [gme] Node version v20.10.0
2023-12-06T04:51:07.684Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-06T04:51:07.684Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-06T04:51:07.690Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.2:8888
2023-12-06T04:51:07.744Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-06T04:51:07.745Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-06T04:51:07.787Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-06T04:51:07.909Z - info: [gme:server:standalone] Server is listening ...
2023-12-06T05:05:16.194Z - info: [gme] Node version v20.10.0
2023-12-06T05:05:16.194Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-06T05:05:16.194Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-06T05:05:16.200Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.2:8888
2023-12-06T05:05:16.252Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-06T05:05:16.253Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-06T05:05:16.276Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-06T05:05:16.396Z - info: [gme:server:standalone] Server is listening ...
2023-12-06T06:20:28.671Z - info: [gme] Node version v20.10.0
2023-12-06T06:20:28.671Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-06T06:20:28.671Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-06T06:20:28.677Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.2:8888
2023-12-06T06:20:28.732Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-06T06:20:28.734Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-06T06:20:28.763Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-06T06:20:28.883Z - info: [gme:server:standalone] Server is listening ...
2023-12-06T23:10:39.479Z - info: [gme] Node version v20.10.0
2023-12-06T23:10:39.480Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-06T23:10:39.480Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-06T23:10:39.485Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://10.74.206.210:8888
2023-12-06T23:10:39.540Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-06T23:10:39.541Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-06T23:10:39.547Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-06T23:10:39.548Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-06T23:11:01.663Z - info: [gme] Node version v20.10.0
2023-12-06T23:11:01.663Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-06T23:11:01.663Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-06T23:11:01.668Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://10.74.206.210:8888
2023-12-06T23:11:01.717Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-06T23:11:01.718Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-06T23:11:01.739Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-06T23:11:01.860Z - info: [gme:server:standalone] Server is listening ...
2023-12-06T23:50:12.865Z - info: [gme] Node version v20.10.0
2023-12-06T23:50:12.865Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-06T23:50:12.865Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-06T23:50:12.870Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://10.74.206.210:8888
2023-12-06T23:50:12.922Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-06T23:50:12.924Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-06T23:50:12.944Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-06T23:50:13.064Z - info: [gme:server:standalone] Server is listening ...
2023-12-06T23:51:27.157Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-06T23:51:27.161Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-06T23:52:15.535Z - info: [gme:server:worker:simpleworker:pid_1475:WorkerFunctions:PluginManagerBase:plugin:samplePlugin] zmq-server listening at port 5555
2023-12-06T23:52:15.678Z - error: [gme:server:worker:simpleworker:pid_1475:WorkerFunctions:PluginManagerBase:plugin:samplePlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/run_plugin.py", line 13, in <module>

2023-12-06T23:52:15.678Z - error: [gme:server:worker:simpleworker:pid_1475:WorkerFunctions:PluginManagerBase:plugin:samplePlugin]     from samplePlugin import samplePlugin
ImportError: cannot import name 'samplePlugin' from 'samplePlugin' (/Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/samplePlugin/__init__.py)

2023-12-06T23:52:15.683Z - error: [gme:server:worker:simpleworker:pid_1475:WorkerFunctions:PluginManagerBase:plugin:samplePlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/run_plugin.py 5555 "#470fe49945f4162129b979b2fa3301965ea81603" "master" "/J/9" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/samplePlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-06T23:52:15.684Z - error: [gme:server:worker:simpleworker:pid_1475:WorkerFunctions] plugin [samplePlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/run_plugin.py 5555 "#470fe49945f4162129b979b2fa3301965ea81603" "master" "/J/9" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/run_plugin.py 5555 "#470fe49945f4162129b979b2fa3301965ea81603" "master" "/J/9" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/samplePlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T08:28:19.211Z - info: [gme] Node version v20.10.0
2023-12-07T08:28:19.212Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T08:28:19.212Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T08:28:19.218Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.3:8888
2023-12-07T08:28:19.273Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T08:28:19.274Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T08:28:19.293Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T08:28:19.413Z - error: [gme:server:standalone] Failed to start server port=8888, code=EADDRINUSE, errno=-48, syscall=listen, address=::, port=8888
2023-12-07T08:29:49.585Z - info: [gme] Node version v20.10.0
2023-12-07T08:29:49.585Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T08:29:49.585Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T08:29:49.591Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.3:8888
2023-12-07T08:29:49.637Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T08:29:49.639Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T08:29:49.653Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T08:29:49.768Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T17:23:46.571Z - info: [gme] Node version v20.10.0
2023-12-07T17:23:46.571Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T17:23:46.571Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T17:23:46.577Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.3:8888
2023-12-07T17:23:46.633Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T17:23:46.634Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T17:23:46.641Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-07T17:23:46.641Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-07T17:25:05.380Z - info: [gme] Node version v20.10.0
2023-12-07T17:25:05.381Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T17:25:05.381Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T17:25:05.386Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.3:8888
2023-12-07T17:25:05.438Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T17:25:05.439Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T17:25:05.463Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T17:25:05.581Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T17:26:25.564Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-07T17:26:25.567Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-07T17:26:27.514Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-07T17:26:27.515Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-07T17:26:27.516Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-07T17:26:27.516Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-07T17:26:27.523Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-07T17:27:22.980Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T17:27:23.162Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 11:27:23,162 - othelloPlugin - INFO - sys.args: ['/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py', '5555', '"#7b4447ee7ac6790d0c8541f51d37a3dda0a4dcb2"', '"master"', '"/n/3"', '""', '""']

2023-12-07T17:27:23.165Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 11:27:23,164 - othelloPlugin - INFO - Connected to tcp://127.0.0.1:5555

2023-12-07T17:27:23.168Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 11:27:23,168 - othelloPlugin - INFO - ActiveNode at "/n/3" has name GameFolder

2023-12-07T17:27:23.187Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 11:27:23,187 - othelloPlugin - INFO - committed :{'status': 'SYNCED', 'hash': '#6244fe3f6f91b0ad6c4168b387a836f4dde1459a'}

2023-12-07T17:27:23.187Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 11:27:23,187 - othelloPlugin - INFO - Disconnected from tcp://127.0.0.1:5555

2023-12-07T17:30:41.662Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T17:30:41.748Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0

Valid Moves for Player 1: []
2023-12-07 11:30:41,748 - othelloPlugin - INFO - sys.args: ['/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py', '5555', '"#6244fe3f6f91b0ad6c4168b387a836f4dde1459a"', '"master"', '"/n/3"', '""', '""']

2023-12-07T17:30:41.752Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 11:30:41,752 - othelloPlugin - INFO - Connected to tcp://127.0.0.1:5555

2023-12-07T17:30:41.757Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 11:30:41,757 - othelloPlugin - INFO - ActiveNode at "/n/3" has name newName

2023-12-07T17:30:41.779Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 11:30:41,779 - othelloPlugin - INFO - committed :{'status': 'SYNCED', 'hash': '#ea911b59bdd07e9e4d96c7b7635fe69b0ed165a2'}

2023-12-07T17:30:41.780Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 11:30:41,779 - othelloPlugin - INFO - Disconnected from tcp://127.0.0.1:5555

2023-12-07T18:02:38.743Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T18:02:38.857Z - error: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 13, in <module>

2023-12-07T18:02:38.858Z - error: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     from othelloPlugin import othelloPlugin
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 86, in <module>
    othello_game.apply_move(move)
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 26, in apply_move
    if move in self.get_valid_moves():
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 44, in get_valid_moves
    highlight_plugin = HighlightValidTilesPlugin(self.game_state_history[-1])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'HighlightValidTilesPlugin' is not defined

2023-12-07T18:02:38.864Z - error: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8dae80acfdbbc3a8ca36e2eb669aed4c97c7d698" "master" "/n/q" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T18:02:38.872Z - error: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8dae80acfdbbc3a8ca36e2eb669aed4c97c7d698" "master" "/n/q" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8dae80acfdbbc3a8ca36e2eb669aed4c97c7d698" "master" "/n/q" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T18:07:25.117Z - info: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T18:07:25.225Z - error: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 13, in <module>

2023-12-07T18:07:25.225Z - error: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     from othelloPlugin import othelloPlugin
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 86, in <module>
    othello_game.apply_move(move)
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 26, in apply_move

2023-12-07T18:07:25.225Z - error: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     if move in self.get_valid_moves():
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 44, in get_valid_moves
    highlight_plugin = HighlightValidTilesPlugin(self.game_state_history[-1])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^

2023-12-07T18:07:25.226Z - error: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] NameError: name 'HighlightValidTilesPlugin' is not defined

2023-12-07T18:07:25.231Z - error: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#1e7eaff0bc6d0c1e5ecb6e9582ca869ccceeaf00" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T18:07:25.231Z - error: [gme:server:worker:simpleworker:pid_1408:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#1e7eaff0bc6d0c1e5ecb6e9582ca869ccceeaf00" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#1e7eaff0bc6d0c1e5ecb6e9582ca869ccceeaf00" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T18:14:14.883Z - info: [gme] Node version v20.10.0
2023-12-07T18:14:14.883Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T18:14:14.883Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T18:14:14.889Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.3:8888
2023-12-07T18:14:14.939Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T18:14:14.941Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T18:14:14.957Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T18:14:15.074Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T18:35:21.701Z - info: [gme:server:worker:simpleworker:pid_1773:WorkerFunctions:PluginManagerBase:plugin:samplePlugin] zmq-server listening at port 5555
2023-12-07T18:35:21.823Z - error: [gme:server:worker:simpleworker:pid_1773:WorkerFunctions:PluginManagerBase:plugin:samplePlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/run_plugin.py", line 13, in <module>

2023-12-07T18:35:21.823Z - error: [gme:server:worker:simpleworker:pid_1773:WorkerFunctions:PluginManagerBase:plugin:samplePlugin]     from samplePlugin import samplePlugin
ImportError: cannot import name 'samplePlugin' from 'samplePlugin' (/Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/samplePlugin/__init__.py)

2023-12-07T18:35:21.828Z - error: [gme:server:worker:simpleworker:pid_1773:WorkerFunctions:PluginManagerBase:plugin:samplePlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/run_plugin.py 5555 "#0d4b8adaa7e30e57bf679211b4f07ae57380e53f" "master" "/J/9" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/samplePlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T18:35:21.830Z - error: [gme:server:worker:simpleworker:pid_1773:WorkerFunctions] plugin [samplePlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/run_plugin.py 5555 "#0d4b8adaa7e30e57bf679211b4f07ae57380e53f" "master" "/J/9" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/run_plugin.py 5555 "#0d4b8adaa7e30e57bf679211b4f07ae57380e53f" "master" "/J/9" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/samplePlugin/samplePlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T18:44:57.741Z - info: [gme] Node version v20.10.0
2023-12-07T18:44:57.741Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T18:44:57.741Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T18:44:57.747Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.3:8888
2023-12-07T18:44:57.802Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T18:44:57.803Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T18:44:57.818Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T18:44:57.939Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T19:04:36.813Z - info: [gme] Node version v20.10.0
2023-12-07T19:04:36.813Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T19:04:36.813Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T19:04:36.819Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.3:8888
2023-12-07T19:04:36.870Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T19:04:36.871Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T19:04:36.889Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T19:04:37.006Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T20:27:47.352Z - info: [gme] Node version v20.10.0
2023-12-07T20:27:47.352Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T20:27:47.352Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T20:27:47.358Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://172.20.10.2:8888
2023-12-07T20:27:47.412Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T20:27:47.414Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:27:47.441Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:27:47.566Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T20:28:24.393Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-07T20:28:24.396Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-07T20:29:17.236Z - info: [gme:server:worker:simpleworker:pid_3303:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T20:29:17.360Z - error: [gme:server:worker:simpleworker:pid_3303:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 13, in <module>

2023-12-07T20:29:17.360Z - error: [gme:server:worker:simpleworker:pid_3303:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     from othelloPlugin import othelloPlugin
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 86, in <module>
    othello_game.apply_move(move)
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 26, in apply_move
    if move in self.get_valid_moves():
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 44, in get_valid_moves
    highlight_plugin = HighlightValidTilesPlugin(self.game_state_history[-1])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'HighlightValidTilesPlugin' is not defined

2023-12-07T20:29:17.366Z - error: [gme:server:worker:simpleworker:pid_3303:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T20:29:17.367Z - error: [gme:server:worker:simpleworker:pid_3303:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T20:32:44.858Z - info: [gme] Node version v20.10.0
2023-12-07T20:32:44.859Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T20:32:44.859Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T20:32:44.864Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://172.20.10.2:8888
2023-12-07T20:32:44.918Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T20:32:44.920Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:32:44.946Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:32:45.066Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T20:32:57.191Z - info: [gme:server:worker:simpleworker:pid_3425:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T20:32:57.297Z - error: [gme:server:worker:simpleworker:pid_3425:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 13, in <module>

2023-12-07T20:32:57.297Z - error: [gme:server:worker:simpleworker:pid_3425:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     from othelloPlugin import othelloPlugin
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 86, in <module>
    othello_game.apply_move(move)
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 26, in apply_move
    if move in self.get_valid_moves():
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 44, in get_valid_moves
    highlight_plugin = HighlightValidTilesPlugin(self.game_state_history[-1])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'HighlightValidTilesPlugin' is not defined

2023-12-07T20:32:57.303Z - error: [gme:server:worker:simpleworker:pid_3425:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T20:32:57.304Z - error: [gme:server:worker:simpleworker:pid_3425:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T20:41:46.788Z - info: [gme] Node version v20.10.0
2023-12-07T20:41:46.788Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T20:41:46.788Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T20:41:46.794Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://172.20.10.2:8888
2023-12-07T20:41:46.847Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T20:41:46.849Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:41:46.870Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:41:46.990Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T20:42:14.915Z - info: [gme:server:worker:simpleworker:pid_3499:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T20:42:15.029Z - error: [gme:server:worker:simpleworker:pid_3499:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 13, in <module>

2023-12-07T20:42:15.029Z - error: [gme:server:worker:simpleworker:pid_3499:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     from othelloPlugin import othelloPlugin
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 19
    Certainly! Below is the updated `__init__.py` file that includes the `OthelloGamePlugin` class along with the other plugins:
             ^
SyntaxError: invalid syntax

2023-12-07T20:42:15.034Z - error: [gme:server:worker:simpleworker:pid_3499:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T20:42:15.036Z - error: [gme:server:worker:simpleworker:pid_3499:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T20:46:43.574Z - info: [gme] Node version v20.10.0
2023-12-07T20:46:43.574Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T20:46:43.574Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T20:46:43.580Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://172.20.10.2:8888
2023-12-07T20:46:43.631Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T20:46:43.633Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:46:43.655Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:46:43.775Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T20:47:01.950Z - info: [gme:server:worker:simpleworker:pid_3540:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T20:47:02.060Z - error: [gme:server:worker:simpleworker:pid_3540:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 13, in <module>

2023-12-07T20:47:02.060Z - error: [gme:server:worker:simpleworker:pid_3540:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     from othelloPlugin import othelloPlugin
ImportError: cannot import name 'othelloPlugin' from 'othelloPlugin' (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py)

2023-12-07T20:47:02.065Z - error: [gme:server:worker:simpleworker:pid_3540:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T20:47:02.067Z - error: [gme:server:worker:simpleworker:pid_3540:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T20:51:31.486Z - info: [gme] Node version v20.10.0
2023-12-07T20:51:31.487Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T20:51:31.487Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T20:51:31.492Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://172.20.10.2:8888
2023-12-07T20:51:31.546Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T20:51:31.548Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:51:31.573Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:51:31.695Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T20:51:53.146Z - info: [gme:server:worker:simpleworker:pid_3657:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T20:51:53.264Z - error: [gme:server:worker:simpleworker:pid_3657:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 13, in <module>

2023-12-07T20:51:53.264Z - error: [gme:server:worker:simpleworker:pid_3657:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     from othelloPlugin import othelloPlugin
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 19
    class OthelloPlugin(PluginBase)::
                                    ^
SyntaxError: invalid syntax

2023-12-07T20:51:53.269Z - error: [gme:server:worker:simpleworker:pid_3657:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T20:51:53.271Z - error: [gme:server:worker:simpleworker:pid_3657:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T20:52:46.806Z - info: [gme] Node version v20.10.0
2023-12-07T20:52:46.806Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T20:52:46.806Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T20:52:46.812Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://172.20.10.2:8888
2023-12-07T20:52:46.867Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T20:52:46.869Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:52:46.885Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:52:47.017Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T20:52:56.645Z - info: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T20:52:56.751Z - error: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 13, in <module>

2023-12-07T20:52:56.751Z - error: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     from othelloPlugin import othelloPlugin
ImportError: cannot import name 'othelloPlugin' from 'othelloPlugin' (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py)

2023-12-07T20:52:56.756Z - error: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T20:52:56.757Z - error: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T20:54:37.752Z - info: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T20:54:37.855Z - info: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 14:54:37,855 - othelloPlugin - INFO - sys.args: ['/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py', '5555', '"#8a5538f1baf49506995fb86689ff6523899b4a9d"', '"master"', '"/n/3"', '""', '""']

2023-12-07T20:54:37.857Z - info: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 14:54:37,857 - othelloPlugin - INFO - Connected to tcp://127.0.0.1:5555

2023-12-07T20:54:37.858Z - error: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 41, in <module>
    plugin = othelloPlugin(webgme, COMMIT_HASH, BRANCH_NAME, ACTIVE_NODE_PATH, ACTIVE_SELECTION_PATHS, NAMESPACE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: othelloPlugin.__init__() takes 2 positional arguments but 7 were given

2023-12-07T20:54:37.863Z - error: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T20:54:37.864Z - error: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T20:57:01.428Z - info: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T20:57:01.547Z - info: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 14:57:01,547 - othelloPlugin - INFO - sys.args: ['/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py', '5555', '"#8a5538f1baf49506995fb86689ff6523899b4a9d"', '"master"', '"/n/3"', '""', '""']

2023-12-07T20:57:01.551Z - info: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 14:57:01,551 - othelloPlugin - INFO - Connected to tcp://127.0.0.1:5555

2023-12-07T20:57:01.552Z - error: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 41, in <module>
    plugin = othelloPlugin(webgme, COMMIT_HASH, BRANCH_NAME, ACTIVE_NODE_PATH, ACTIVE_SELECTION_PATHS, NAMESPACE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 21, in __init__

2023-12-07T20:57:01.552Z - error: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     self.game_state_history = [initial_game_state]
                               ^^^^^^^^^^^^^^^^^^
NameError: name 'initial_game_state' is not defined

2023-12-07T20:57:01.558Z - error: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T20:57:01.558Z - error: [gme:server:worker:simpleworker:pid_3688:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T20:57:18.939Z - info: [gme] Node version v20.10.0
2023-12-07T20:57:18.939Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T20:57:18.939Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T20:57:18.945Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://172.20.10.2:8888
2023-12-07T20:57:18.996Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T20:57:18.997Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:57:19.011Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T20:57:19.133Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T20:57:28.468Z - info: [gme:server:worker:simpleworker:pid_3757:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T20:57:28.543Z - info: [gme:server:worker:simpleworker:pid_3757:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 14:57:28,542 - othelloPlugin - INFO - sys.args: ['/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py', '5555', '"#8a5538f1baf49506995fb86689ff6523899b4a9d"', '"master"', '"/n/3"', '""', '""']

2023-12-07T20:57:28.545Z - info: [gme:server:worker:simpleworker:pid_3757:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 14:57:28,545 - othelloPlugin - INFO - Connected to tcp://127.0.0.1:5555

2023-12-07T20:57:28.545Z - error: [gme:server:worker:simpleworker:pid_3757:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 41, in <module>
    plugin = othelloPlugin(webgme, COMMIT_HASH, BRANCH_NAME, ACTIVE_NODE_PATH, ACTIVE_SELECTION_PATHS, NAMESPACE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-12-07T20:57:28.545Z - error: [gme:server:worker:simpleworker:pid_3757:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]   File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 21, in __init__

2023-12-07T20:57:28.546Z - error: [gme:server:worker:simpleworker:pid_3757:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     self.game_state_history = [initial_game_state]
                               ^^^^^^^^^^^^^^^^^^
NameError: name 'initial_game_state' is not defined

2023-12-07T20:57:28.551Z - error: [gme:server:worker:simpleworker:pid_3757:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T20:57:28.552Z - error: [gme:server:worker:simpleworker:pid_3757:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T21:00:05.247Z - info: [gme] Node version v20.10.0
2023-12-07T21:00:05.248Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T21:00:05.248Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T21:00:05.253Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://172.20.10.2:8888
2023-12-07T21:00:05.305Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T21:00:05.307Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T21:00:05.324Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T21:00:05.447Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T21:00:13.034Z - info: [gme:server:worker:simpleworker:pid_3795:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T21:00:13.141Z - info: [gme:server:worker:simpleworker:pid_3795:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 15:00:13,141 - othelloPlugin - INFO - sys.args: ['/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py', '5555', '"#8a5538f1baf49506995fb86689ff6523899b4a9d"', '"master"', '"/n/3"', '""', '""']

2023-12-07T21:00:13.144Z - info: [gme:server:worker:simpleworker:pid_3795:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 15:00:13,144 - othelloPlugin - INFO - Connected to tcp://127.0.0.1:5555

2023-12-07T21:00:13.144Z - error: [gme:server:worker:simpleworker:pid_3795:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 41, in <module>
    plugin = othelloPlugin(webgme, COMMIT_HASH, BRANCH_NAME, ACTIVE_NODE_PATH, ACTIVE_SELECTION_PATHS, NAMESPACE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 21, in __init__
    self.game_state_history = [initial_game_state]

2023-12-07T21:00:13.144Z - error: [gme:server:worker:simpleworker:pid_3795:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]                                ^^^^^^^^^^^^^^^^^^
NameError: name 'initial_game_state' is not defined

2023-12-07T21:00:13.150Z - error: [gme:server:worker:simpleworker:pid_3795:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T21:00:13.151Z - error: [gme:server:worker:simpleworker:pid_3795:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-07T21:01:56.375Z - info: [gme] Node version v20.10.0
2023-12-07T21:01:56.375Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T21:01:56.375Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T21:01:56.381Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://172.20.10.2:8888
2023-12-07T21:01:56.428Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T21:01:56.430Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T21:01:56.448Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T21:01:56.568Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T21:05:05.128Z - info: [gme] Node version v20.10.0
2023-12-07T21:05:05.128Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T21:05:05.128Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T21:05:05.134Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://172.20.10.2:8888
2023-12-07T21:05:05.189Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T21:05:05.190Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T21:05:05.208Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T21:05:05.329Z - info: [gme:server:standalone] Server is listening ...
2023-12-07T21:05:10.760Z - info: [gme:server:worker:simpleworker:pid_3871:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T21:05:10.865Z - error: [gme:server:worker:simpleworker:pid_3871:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 13, in <module>

2023-12-07T21:05:10.866Z - error: [gme:server:worker:simpleworker:pid_3871:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     from othelloPlugin import othelloPlugin
ImportError: cannot import name 'othelloPlugin' from 'othelloPlugin' (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py)

2023-12-07T21:05:10.871Z - error: [gme:server:worker:simpleworker:pid_3871:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T21:05:10.872Z - error: [gme:server:worker:simpleworker:pid_3871:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T22:30:00.159Z - info: [gme:server:worker:simpleworker:pid_3871:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-07T22:30:00.282Z - info: [gme:server:worker:simpleworker:pid_3871:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 16:30:00,282 - othelloPlugin - INFO - sys.args: ['/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py', '5555', '"#8a5538f1baf49506995fb86689ff6523899b4a9d"', '"master"', '"/n/3"', '""', '""']

2023-12-07T22:30:00.284Z - info: [gme:server:worker:simpleworker:pid_3871:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 16:30:00,284 - othelloPlugin - INFO - Connected to tcp://127.0.0.1:5555

2023-12-07T22:30:00.324Z - error: [gme:server:worker:simpleworker:pid_3871:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 41, in <module>
    plugin = othelloPlugin(webgme, COMMIT_HASH, BRANCH_NAME, ACTIVE_NODE_PATH, ACTIVE_SELECTION_PATHS, NAMESPACE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 21, in __init__
    self.game_state_history = [initial_game_state]
                               ^^^^^^^^^^^^^^^^^^
NameError: name 'initial_game_state' is not defined

2023-12-07T22:30:00.324Z - error: [gme:server:worker:simpleworker:pid_3871:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T22:30:00.325Z - error: [gme:server:worker:simpleworker:pid_3871:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
2023-12-07T23:53:41.858Z - info: [gme] Node version v20.10.0
2023-12-07T23:53:41.858Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T23:53:41.858Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T23:53:41.864Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.3:8888
2023-12-07T23:53:41.922Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T23:53:41.924Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T23:53:41.930Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-07T23:53:41.930Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-07T23:53:59.827Z - info: [gme] Node version v20.10.0
2023-12-07T23:53:59.828Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-07T23:53:59.828Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-07T23:53:59.833Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.2.3:8888
2023-12-07T23:53:59.881Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-07T23:53:59.882Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T23:53:59.914Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-07T23:54:00.053Z - info: [gme:server:standalone] Server is listening ...
2023-12-08T00:42:45.788Z - info: [gme] Node version v20.10.0
2023-12-08T00:42:45.789Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-08T00:42:45.789Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-08T00:42:45.794Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://10.74.206.210:8888
2023-12-08T00:42:45.847Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-08T00:42:45.849Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-08T00:42:45.868Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-08T00:42:46.001Z - error: [gme:server:standalone] Failed to start server port=8888, code=EADDRINUSE, errno=-48, syscall=listen, address=::, port=8888
2023-12-08T00:43:13.647Z - info: [gme] Node version v20.10.0
2023-12-08T00:43:13.648Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-08T00:43:13.648Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-08T00:43:13.653Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://10.74.206.210:8888
2023-12-08T00:43:13.699Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-08T00:43:13.700Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-08T00:43:13.715Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-08T00:43:13.833Z - error: [gme:server:standalone] Failed to start server port=8888, code=EADDRINUSE, errno=-48, syscall=listen, address=::, port=8888
2023-12-08T00:44:06.198Z - info: [gme] Node version v20.10.0
2023-12-08T00:44:06.198Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-08T00:44:06.198Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-08T00:44:06.204Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://10.74.206.210:8888
2023-12-08T00:44:06.255Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-08T00:44:06.257Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-08T00:44:06.275Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-08T00:44:06.396Z - info: [gme:server:standalone] Server is listening ...
2023-12-08T00:45:52.323Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-08T00:45:52.512Z - error: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Traceback (most recent call last):
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py", line 13, in <module>

2023-12-08T00:45:52.512Z - error: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin]     from othelloPlugin import othelloPlugin
  File "/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin/__init__.py", line 1, in <module>
    class othelloPlugin(PluginBase):
                        ^^^^^^^^^^
NameError: name 'PluginBase' is not defined

2023-12-08T00:45:52.517Z - error: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-08T00:45:52.518Z - error: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions] plugin [othelloPlugin] failed with error message=python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1., stack=Error: python /Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py 5555 "#8a5538f1baf49506995fb86689ff6523899b4a9d" "master" "/n/3" "" "" exited with code 1.
    at ChildProcess.<anonymous> (/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/othelloPlugin.js:99:37)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2023-12-08T00:47:50.362Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-08T00:47:50.484Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:47:50,484 - othelloPlugin - INFO - sys.args: ['/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py', '5555', '"#8a5538f1baf49506995fb86689ff6523899b4a9d"', '"master"', '"/n/3"', '""', '""']

2023-12-08T00:47:50.487Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:47:50,487 - othelloPlugin - INFO - Connected to tcp://127.0.0.1:5555

2023-12-08T00:47:50.492Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:47:50,492 - othelloPlugin - INFO - name: GameFolder

2023-12-08T00:47:50.492Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:47:50,492 - othelloPlugin - WARNING - pos : {'x': 862, 'y': 58}

2023-12-08T00:47:50.493Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:47:50,493 - othelloPlugin - ERROR - guid: 57406c5f-a879-de22-a2c1-68095ae75845

2023-12-08T00:47:50.494Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:47:50,494 - othelloPlugin - INFO - Childs of Game State []

2023-12-08T00:47:50.494Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:47:50,494 - othelloPlugin - INFO - 0

2023-12-08T00:47:50.494Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:47:50,494 - othelloPlugin - INFO - This is the next Gamestate : <bound method Core.get_pointer_path of <webgme_bindings.core.Core object at 0x1036e7010>>

2023-12-08T00:47:50.495Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:47:50,495 - othelloPlugin - INFO - Can't undo initial game state 

2023-12-08T00:47:50.495Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:47:50,495 - othelloPlugin - INFO - Disconnected from tcp://127.0.0.1:5555

2023-12-08T00:48:42.210Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-08T00:48:42.303Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:48:42,303 - othelloPlugin - INFO - sys.args: ['/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py', '5555', '"#8a5538f1baf49506995fb86689ff6523899b4a9d"', '"master"', '"/n/3"', '""', '""']

2023-12-08T00:48:42.306Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:48:42,305 - othelloPlugin - INFO - Connected to tcp://127.0.0.1:5555

2023-12-08T00:48:42.309Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:48:42,308 - othelloPlugin - INFO - name: GameFolder

2023-12-08T00:48:42.309Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:48:42,309 - othelloPlugin - WARNING - pos : {'x': 862, 'y': 58}

2023-12-08T00:48:42.309Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:48:42,309 - othelloPlugin - ERROR - guid: 57406c5f-a879-de22-a2c1-68095ae75845

2023-12-08T00:48:42.310Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:48:42,310 - othelloPlugin - INFO - Childs of Game State []

2023-12-08T00:48:42.310Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:48:42,310 - othelloPlugin - INFO - 0

2023-12-08T00:48:42.311Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:48:42,310 - othelloPlugin - INFO - This is the next Gamestate : <bound method Core.get_pointer_path of <webgme_bindings.core.Core object at 0x10149f010>>

2023-12-08T00:48:42.311Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:48:42,311 - othelloPlugin - INFO - Can't undo initial game state 

2023-12-08T00:48:42.311Z - info: [gme:server:worker:simpleworker:pid_2065:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-07 18:48:42,311 - othelloPlugin - INFO - Disconnected from tcp://127.0.0.1:5555

2023-12-09T21:11:15.855Z - info: [gme] Node version v20.10.0
2023-12-09T21:11:15.855Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-09T21:11:15.855Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-09T21:11:15.861Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-09T21:11:15.916Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-09T21:11:15.918Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-09T21:11:15.926Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-09T21:11:15.926Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-09T21:11:33.102Z - info: [gme] Node version v20.10.0
2023-12-09T21:11:33.102Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-09T21:11:33.102Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-09T21:11:33.108Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-09T21:11:33.155Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-09T21:11:33.157Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-09T21:11:33.180Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-09T21:11:33.301Z - info: [gme:server:standalone] Server is listening ...
2023-12-09T21:12:14.521Z - info: [gme:server:worker:simpleworker:pid_1835:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-09T21:12:14.697Z - info: [gme:server:worker:simpleworker:pid_1835:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-09 13:12:14,696 - othelloPlugin - INFO - sys.args: ['/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py', '5555', '"#d86d1bd1bb8c4401cf8eb0ad6236e98c312a8ee4"', '"master"', '""', '""', '""']

2023-12-09T21:12:14.699Z - info: [gme:server:worker:simpleworker:pid_1835:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-09 13:12:14,699 - othelloPlugin - INFO - Connected to tcp://127.0.0.1:5555

2023-12-09T21:12:14.703Z - info: [gme:server:worker:simpleworker:pid_1835:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-09 13:12:14,703 - othelloPlugin - INFO - name: ROOT

2023-12-09T21:12:14.703Z - info: [gme:server:worker:simpleworker:pid_1835:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-09 13:12:14,703 - othelloPlugin - WARNING - pos : None

2023-12-09T21:12:14.703Z - info: [gme:server:worker:simpleworker:pid_1835:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-09 13:12:14,703 - othelloPlugin - ERROR - guid: 03d36072-9e09-7866-cb4e-d0a36ff825f6

2023-12-09T21:12:14.850Z - info: [gme:server:worker:simpleworker:pid_1835:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-09 13:12:14,850 - othelloPlugin - INFO - Childs of Game State ['/1', '/n', '/J']

2023-12-09T21:12:14.852Z - info: [gme:server:worker:simpleworker:pid_1835:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-09 13:12:14,852 - othelloPlugin - INFO - 0

2023-12-09T21:12:14.852Z - info: [gme:server:worker:simpleworker:pid_1835:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-09 13:12:14,852 - othelloPlugin - INFO - This is the next Gamestate : <bound method Core.get_pointer_path of <webgme_bindings.core.Core object at 0x100b97010>>

2023-12-09T21:12:14.853Z - info: [gme:server:worker:simpleworker:pid_1835:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-09 13:12:14,853 - othelloPlugin - INFO - Can't undo initial game state 

2023-12-09T21:12:14.853Z - info: [gme:server:worker:simpleworker:pid_1835:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-09 13:12:14,853 - othelloPlugin - INFO - Disconnected from tcp://127.0.0.1:5555

2023-12-09T21:34:05.969Z - info: [gme] Node version v20.10.0
2023-12-09T21:34:05.970Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-09T21:34:05.970Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-09T21:34:05.975Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-09T21:34:06.027Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-09T21:34:06.029Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-09T21:34:06.047Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-09T21:34:06.169Z - info: [gme:server:standalone] Server is listening ...
2023-12-10T07:49:37.888Z - info: [gme] Node version v20.10.0
2023-12-10T07:49:37.888Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T07:49:37.888Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T07:49:37.894Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://172.20.10.2:8888
2023-12-10T07:49:37.955Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T07:49:37.957Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T07:49:37.963Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-10T07:49:37.963Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T07:56:06.023Z - info: [gme] Node version v20.10.0
2023-12-10T07:56:06.023Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T07:56:06.023Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T07:56:06.029Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T07:56:06.091Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T07:56:06.092Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T07:56:06.100Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-10T07:56:06.101Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T07:56:15.545Z - info: [gme] Node version v20.10.0
2023-12-10T07:56:15.545Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T07:56:15.545Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T07:56:15.551Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T07:56:15.597Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T07:56:15.598Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T07:56:15.604Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-10T07:56:15.604Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T07:56:27.010Z - info: [gme] Node version v20.10.0
2023-12-10T07:56:27.010Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T07:56:27.010Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T07:56:27.016Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T07:56:27.062Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T07:56:27.064Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T07:56:27.071Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-10T07:56:27.071Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T07:56:35.825Z - info: [gme] Node version v20.10.0
2023-12-10T07:56:35.826Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T07:56:35.826Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T07:56:35.830Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T07:56:35.876Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T07:56:35.877Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T07:56:35.883Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-10T07:56:35.883Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T07:56:48.622Z - info: [gme] Node version v20.10.0
2023-12-10T07:56:48.622Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T07:56:48.622Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T07:56:48.628Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T07:56:48.672Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T07:56:48.674Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T07:56:48.680Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-10T07:56:48.680Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T07:57:09.561Z - info: [gme] Node version v20.10.0
2023-12-10T07:57:09.562Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T07:57:09.562Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T07:57:09.569Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T07:57:09.614Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T07:57:09.616Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T07:57:09.624Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-10T07:57:09.624Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T07:57:30.651Z - info: [gme] Node version v20.10.0
2023-12-10T07:57:30.652Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T07:57:30.652Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T07:57:30.657Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T07:57:30.702Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T07:57:30.703Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T07:57:30.709Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-10T07:57:30.710Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T07:57:38.609Z - info: [gme] Node version v20.10.0
2023-12-10T07:57:38.610Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T07:57:38.610Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T07:57:38.614Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T07:57:38.658Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T07:57:38.660Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T07:57:38.665Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-10T07:57:38.666Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T07:58:02.301Z - info: [gme] Node version v20.10.0
2023-12-10T07:58:02.301Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T07:58:02.301Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T07:58:02.307Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T07:58:02.357Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T07:58:02.358Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T07:58:02.372Z - warn: [gme:server:auth:gmeauth] User "guest" was not found. We will attempt to create it automatically.
2023-12-10T07:58:02.460Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T07:58:02.585Z - info: [gme:server:standalone] Server is listening ...
2023-12-10T08:08:14.981Z - info: [gme] Node version v20.10.0
2023-12-10T08:08:14.981Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T08:08:14.981Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T08:08:14.987Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T08:08:15.034Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T08:08:15.036Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T08:08:15.044Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-10T08:08:15.045Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T08:10:07.382Z - info: [gme] Node version v20.10.0
2023-12-10T08:10:07.382Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T08:10:07.382Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T08:10:07.389Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T08:10:07.451Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T08:10:07.453Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T08:10:07.465Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  name: 'MongoNetworkError'
}]
2023-12-10T08:10:07.465Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T08:10:15.608Z - info: [gme] Node version v20.10.0
2023-12-10T08:10:15.608Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T08:10:15.608Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T08:10:15.614Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T08:10:15.669Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T08:10:15.671Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T08:10:15.683Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  name: 'MongoNetworkError'
}]
2023-12-10T08:10:15.683Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T08:11:53.531Z - info: [gme] Node version v20.10.0
2023-12-10T08:11:53.531Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T08:11:53.531Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T08:11:53.536Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T08:11:53.586Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T08:11:53.587Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T08:11:53.596Z - error: [gme:server:auth:gmeauth] MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  name: 'MongoNetworkError'
}]
2023-12-10T08:11:53.596Z - error: [gme:server:standalone] Cannot start server... name=MongoNetworkError
2023-12-10T08:12:35.597Z - info: [gme] Node version v20.10.0
2023-12-10T08:12:35.597Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/miniproject/server.log
2023-12-10T08:12:35.597Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/miniproject/server-error.log
2023-12-10T08:12:35.603Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T08:12:35.650Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/miniproject/blob-local-storage
2023-12-10T08:12:35.651Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T08:12:35.666Z - warn: [gme:server:auth:gmeauth] User "guest" was not found. We will attempt to create it automatically.
2023-12-10T08:12:35.755Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T08:12:35.879Z - info: [gme:server:standalone] Server is listening ...
2023-12-10T08:13:16.253Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-10T08:13:16.257Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close processing
2023-12-10T08:13:33.976Z - info: [gme:server:worker:simpleworker:pid_2081:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] zmq-server listening at port 5555
2023-12-10T08:13:34.198Z - info: [gme:server:worker:simpleworker:pid_2081:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-10 00:13:34,197 - othelloPlugin - INFO - sys.args: ['/Users/sandhyavenkataramaiah/miniproject/src/plugins/othelloPlugin/run_plugin.py', '5555', '"#423a80893a81b333699767cae0e2370bf5c9f769"', '"master"', '""', '""', '""']

2023-12-10T08:13:34.200Z - info: [gme:server:worker:simpleworker:pid_2081:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-10 00:13:34,200 - othelloPlugin - INFO - Connected to tcp://127.0.0.1:5555

2023-12-10T08:13:34.204Z - info: [gme:server:worker:simpleworker:pid_2081:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-10 00:13:34,204 - othelloPlugin - INFO - name: ROOT

2023-12-10T08:13:34.205Z - info: [gme:server:worker:simpleworker:pid_2081:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-10 00:13:34,205 - othelloPlugin - WARNING - pos : None

2023-12-10T08:13:34.205Z - info: [gme:server:worker:simpleworker:pid_2081:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-10 00:13:34,205 - othelloPlugin - ERROR - guid: 03d36072-9e09-7866-cb4e-d0a36ff825f6

2023-12-10T08:13:34.348Z - info: [gme:server:worker:simpleworker:pid_2081:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-10 00:13:34,348 - othelloPlugin - INFO - Childs of Game State ['/1', '/n', '/J']

2023-12-10T08:13:34.350Z - info: [gme:server:worker:simpleworker:pid_2081:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-10 00:13:34,350 - othelloPlugin - INFO - 0

2023-12-10T08:13:34.350Z - info: [gme:server:worker:simpleworker:pid_2081:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-10 00:13:34,350 - othelloPlugin - INFO - This is the next Gamestate : <bound method Core.get_pointer_path of <webgme_bindings.core.Core object at 0x10579f010>>

2023-12-10T08:13:34.351Z - info: [gme:server:worker:simpleworker:pid_2081:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-10 00:13:34,350 - othelloPlugin - INFO - Can't undo initial game state 

2023-12-10T08:13:34.351Z - info: [gme:server:worker:simpleworker:pid_2081:WorkerFunctions:PluginManagerBase:plugin:othelloPlugin] 2023-12-10 00:13:34,350 - othelloPlugin - INFO - Disconnected from tcp://127.0.0.1:5555

2023-12-10T09:20:03.192Z - info: [gme] Node version v20.10.0
2023-12-10T09:20:03.193Z - info: [gme] Logfile [ info ] : /Users/sandhyavenkataramaiah/Documents/miniproject/server.log
2023-12-10T09:20:03.193Z - info: [gme] Logfile [ error ] : /Users/sandhyavenkataramaiah/Documents/miniproject/server-error.log
2023-12-10T09:20:03.198Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://192.168.0.144:8888
2023-12-10T09:20:03.249Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /Users/sandhyavenkataramaiah/Documents/miniproject/blob-local-storage
2023-12-10T09:20:03.250Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T09:20:03.267Z - info: [gme:server:standalone:mongo] connecting to: mongodb://127.0.0.1:27017/webgme_my_app
2023-12-10T09:20:03.389Z - info: [gme:server:standalone] Server is listening ...
